language: node_js

node_js:
    - '8'

# only cli branch
branches:
    only:
        - master

cache:
    directories:
        - node_modules

before_install:

install:
    - npm install

script:
    - npm run build

deploy:
  local_dir: ./public
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master