language: node_js

node_js:
    - 4.4.4

# only cli branch
branches:
    only:
        - master

cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run build

after_script:
    - cd ./public
    - git init
    - git config user.name "${U_NAME}"
    - git config user.email "${U_EMAIL}"
    - git add .
    - git commit -m "Update tools"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}